---

### minimum params:
### cce_provisioning_inventory_hosts_pattern (type: string - the target ansible group to install the products)

################################################################
## Product install using installer
################################################################

- hosts: "{{ cce_provisioning_inventory_hosts_pattern }}"
  become: true
  tasks:
    - import_role: 
        name: provision-with-installer
      vars:
        provision_action: setupfiles
      tags:
        - sysprep-install

    - import_role: 
        name: provision-with-installer
      vars:
        provision_action: runinstall
      become: true
      become_user: "{{ webmethods_user }}"
      tags:
        - install

################################################################
## After Install Run-As-Root
################################################################

- import_playbook: sagenv-common-webmethods-postinstall.yaml
  vars:
    cce_provisioning_postinstall_webmethods: true
    cce_provisioning_postinstall_service_setup: false
    cce_provisioning_postinstall_reboot: false
  tags:
    - postinstall