---

### minimum params:
### cce_provisioning_command_central_hosts (the host(s) where command central is - defaults to "commandcentral")
### cce_provisioning_inventory_hosts_pattern (type: string - the target ansible group to install the CCE template)
### cce_provisioning_inventory_hosts_property (type: string - the property to lookup to find the actual network host of an alias)
### cce_provisioning_template (type: string - the name or path to the CCE template)
### cce_provisioning_properties (type: string - the name of the properties file to load with the CCE template)
### cce_provisioning_template_params (type: dictionary - the dynamic params to apply with the CCE template)
### cce_provisioning_template_params_secure (type: dictionary - the dynamic secure params to apply with the CCE template - the main difference is that these params will not be printed to log outputs)
### cce_provisioning_postinstall_webmethods (type: boolean)

- import_playbook: sagenv-common-webmethods-load-vars.yaml
  tags:
    - always
    
- hosts: "{{ cce_provisioning_command_central_hosts | default('commandcentral') }}"
  become: true
  tasks:
    - name: Provisionning {{ cce_provisioning_template }}
      command: echo "Provisioning {{ cce_provisioning_template }} on inventory groups {{ cce_provisioning_target_hostgroups | default('undefined') }}"
      tags:
        - always
    - name: Print the params
      debug:
        msg:
        - "Running webmethods producct provisoning with:"
        - "cce_provisioning_inventory_hosts_pattern = {{ cce_provisioning_inventory_hosts_pattern | default('undefined') }}"
        - "cce_provisioning_inventory_hosts_property = {{ cce_provisioning_inventory_hosts_property | default('undefined') }}"
        - "cce_provisioning_template = {{ cce_provisioning_template | default('undefined') }}"
        - "cce_provisioning_properties = {{ cce_provisioning_properties | default('undefined') }}"
        - "cce_provisioning_template_params = {{ cce_provisioning_template_params | default('undefined') }}"
        - "cce_provisioning_template_params_secure = ******************"
        - "cce_provisioning_postinstall_webmethods = {{ cce_provisioning_postinstall_webmethods | default('undefined') }}"
      tags:
        - always
    - import_role: 
        name: prepare-cce-provisoning
      vars:
        cce_prep_type: "code"
        cce_copy_content: true
      tags:
        - always

#install stack
- hosts: "{{ cce_provisioning_command_central_hosts | default('commandcentral') }}"
  become: true
  become_user: "{{ cce_owner }}"
  tasks:
    - import_role: 
        name: provision-with-cce
      vars:
        run_dir: "{{ cce_provisioning_code_path }}"
        inventory_pattern: "{{ cce_provisioning_inventory_hosts_pattern }}"
        hosts_property: "{{ cce_provisioning_inventory_hosts_property }}"
        aliases_property: "{{ cce_provisioning_inventory_aliases_property }}"
        aliasmapping_prefix: "{{ cce_provisioning_inventory_aliasmapping_prefix }}"
        aliasmapping_delimiter: "{{ cce_provisioning_inventory_aliasmapping_delimiter }}"
        template: "{{ cce_provisioning_template }}"
        properties: "{{ cce_provisioning_properties }}"
        template_params: "{{ cce_provisioning_template_params }}"
        template_params_secure: "{{ cce_provisioning_template_params_secure }}"
  tags:
    - install

#wM post install script to run as root
- hosts: "{{ cce_provisioning_inventory_hosts_pattern }}"
  become: true
  tasks:
    - import_role: 
        name: post-install-webmethods
      vars:
        postinstall_do_reboot: false
      when: cce_provisioning_postinstall_webmethods|bool
  tags:
    - postinstall